version: 2
updates:
  # ===========================
  # NPM Updates (Daily)
  # ===========================
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(npm): [skip ci]"
    labels:
      - "dependencies"
      - "npm"
    versioning-strategy: increase
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
        ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-patch"]

  # ===========================
  # GitHub Actions Updates (Daily)
  # ===========================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build(actions): [skip ci]"
    labels:
      - "dependencies"
      - "github-actions"
    versioning-strategy: increase
    groups:
      actions-dependencies:
        patterns:
          - "*"
        ignore:
          - dependency-name: "*"
            update-types: ["version-update:semver-patch"]
