codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
  strict_yaml_branch: main
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

github_checks:
  annotations: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: false
