name: Release

on:
  push:
    branches:
      - main

jobs:
  prepare:
    uses: SP-Packages/actions/.github/workflows/code-quality.yml@v1.1.1
    with:
      VERBOSE: true

  test:
    needs: prepare
    uses: SP-Packages/actions/.github/workflows/code-testing.yml@v1.1.1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      SLUG: SP-Packages/hello-world
    permissions:
      contents: read
      pull-requests: write

  release:
    needs: test
    uses: SP-Packages/actions/.github/workflows/semantic-release.yml@v1.1.1
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write

  rebase:
    needs: prepare
    uses: SP-Packages/actions/.github/workflows/rebase-develop.yml@v1.1.1
    permissions:
      contents: write
